---
version: '3'
services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - "3307:3307"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
